Check for CHECKMARX_TEAM variable

diff --git a/.github/workflows/checkmarx.yaml b/.github/workflows/checkmarx.yaml
--- a/.github/workflows/checkmarx.yaml
+++ b/.github/workflows/checkmarx.yaml
@@ -23,7 +23,13 @@ jobs:
           ref: ${{ github.event.client_payload.pull_request.head.sha }}
 
       - name: Remove unneeded files
-        run: rm -rf db spec script/data_migrations ./public/images/seconds_animated_60.gif test tests
+        run: |
+          rm -rf db spec script/data_migrations ./public/images/seconds_animated_60.gif test tests
+          find . -name __tests__ -o -name __mocks__ -print0 | xargs -0 rm -rf
+
+      - name: Verify environment
+        run: |
+          if [ "${{ secrets.CHECKMARX_TEAM }}" == '' ]; then echo "Error: CHECKMARX_TEAM was not set"; exit 1;fi
 
       - name: Checkmarx CxFlow Action
         uses: checkmarx-ts/checkmarx-cxflow-github-action@v1.5
